### ISSUE TITLE
Fixtures are flaky

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#2640]
### Describe the bug
createfixtures may fail randomly in CI. I got this error:

<details>
<summary>Error</summary>

```
Creating a membergroup
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "activemembers_committee_name_en_key"
DETAIL:  Key (name)=(Amet) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/concrexit/concrexit/website/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/runner/work/concrexit/concrexit/website/utils/management/commands/createfixtures.py", line 702, in handle
    self.create_member_group(Society)
  File "/home/runner/work/concrexit/concrexit/website/utils/management/commands/createfixtures.py", line 215, in create_member_group
    member_group.photo.save(member_group.name + ".jpeg", ContentFile(icon))
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/fields/files.py", line 98, in save
    self.instance.save()
  File "/home/runner/work/concrexit/concrexit/website/activemembers/models.py", line 110, in save
    super().save(**kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/base.py", line 862, in save_base
    parent_inserted = self._save_parents(cls, using, update_fields)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/base.py", line 904, in _save_parents
    updated = self._save_table(
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/.cache/pypoetry/virtualenvs/concrexit-HBEO5f-9-py3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "activemembers_committee_name_en_key"
DETAIL:  Key (name)=(Amet) already exists.

make: *** [Makefile:195: fixtures] Error 1
```

</details>

### How to reproduce
It randomly happens

### Expected behaviour
Createfixtures always works

### Additional context
It happened here: https://github.com/svthalia/concrexit/actions/runs/3380853146/jobs/5614104395

**Comment by ColonelPhantom** [comment]
In this case, it seems like the code tries to generate two committees that are both called "Amet".

**Comment by JobDoesburg** [comment]
Also note that fixtures dont always clean() right now. We create events that dont validate actually.

**Comment by ColonelPhantom** [comment]
I just saw this https://github.com/svthalia/concrexit/actions/runs/4493757940/jobs/7905375790 which seems to be a problem with fixtures, while this commit was merged into it. So it seems there's still something flaky about the fixtures, unfortunately.
